<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
   
<h2>Bank Form</h2>
<form action="/bank" method="POST">

    <label for="code">Code</label>
    <input type="text" name="code" />

    <label for="address">Address</label>
    <input type="text" name="address">

    <label for="name">Name</label>
    <input type="text" name="name">

    <button type="submit">Submit</button>
</form>
