<?php session_start();?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<?php

if(!isset($_SESSION['name']) && !isset($_SESSION['password']))
{
    header("location: login");
}
  
use App\Models\Account;

$sql = "SELECT accounts.* FROM `accounts` where accounts.customer_id = ". $_SESSION['id'];

$account = new Account();

$stmt = $account->conn->query($sql);

$users = [];    

while($row = $stmt->fetch())
{
    $users[] = $row;
}

?>

<div class="table-responsive">

    <table class="table table-responsive">
        <tr>
            <th>Account number</th>
            <th>balance</th>
            <th>Account type</th>
            <th>description</th>
        </tr>

        <?php foreach($users as $user): ?>

            <tr>
                    <td><?= $user['id'] ?></td>
                    <td><?= $user['balance'] ?></td>
                    <td><?= $user['account_type'] ?></td>
                    <td><?= $user['description'] ?></td>
            </tr>

        <?php endforeach ?>
            
            <form action="/customer" method="POST">
                <tr>
                    <td>id</td>
                    <td>balance</td>
                    <td><input type="text" name="account_type"></td>
                    <td><input type="text" name="description"></td>
                    <td><input type="submit" name="submit"></td>  
                </tr>
            </form>
            
    </table>



</div>

<a href="logout">Logout</a>