<?php

use App\Models\Account;
use App\Models\Transactions;


if(!isset($_SESSION['email']))
{
    header("location: login");
}
  
$accountsQuery = "SELECT accounts.* FROM `accounts` where accounts.customer_id = ". $_SESSION['id'];

$accountModel = new Account();

$accountsResult = $accountModel
    ->conn
    ->query($accountsQuery)
    ->fetchAll();

$transactionsQuery = "SELECT DISTINCT atr.* FROM atm_transactions atr JOIN accounts acc ON acc.`id` =  atr.`from_account_id` and acc.`customer_id` = '{$_SESSION['id']}' or acc.`id` =  atr.`to_account_id` and acc.`customer_id` = '{$_SESSION['id']}'";

$transactionModel = new Transactions();
$transactionsResult = $transactionModel
        ->conn
        ->query($transactionsQuery)
        ->fetchAll();

?>

<head>
    <title>Bank</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
<div class="table-responsive">

    <table class="table table-responsive">
        <tr>
            <th>Account number</th>
            <th>balance</th>
            <th>Account type</th>
            <th>description</th>
        </tr>

        <?php foreach($accountsResult as $account): ?>

            <tr>
                    <td><?= $account['id'] ?></td>
                    <td><?= $account['balance'] ?></td>
                    <td><?= $account['account_type'] ?></td>
                    <td><?= $account['description'] ?></td>
                    <td>
                    <input type="submit" data-accountNumberBtn="<?php echo $account['id'] ?>" onclick="accountNumber($(this))" name="show" value="Transact">
                    </td>
            </tr>

        <?php endforeach ?>
            
            <form action="/customer" method="POST">
                <tr>
                    <td>id</td>
                    <td>balance</td>
                    <td><input type="text" name="account_type"></td>
                    <td><input type="text" name="description"></td>
                    <td><input type="submit" name="submit"></td>
                </tr>
            </form>
            
    </table>

</div>

<form action="/transact" method="POST" class="<?php echo $hide; ?>">

    <input type="hidden" id="accountNumberForTransact" value="" name="acc">

    <label for="">Account you want to transact: </label>
    <input type="text" name="account_id">

    <label for="">Ammount of money you want to send(in cent): </label>
    <input type="number" name="amount_of_money">

    <input type="submit" name="transact">

</form>

<div class="table-responsive">

    <table class="table table-responsive">
        <tr>
            <th>Transaction ID</th>
            <th>balance</th>
            <th>From</th>
            <th>To</th>
            <th>Created at</th>
        </tr>

        <?php foreach($transactionsResult as $transaction): ?>

            <tr>
                    <td><?= $transaction['id'] ?></td>
                    <td><?= $transaction['balance'] ?></td>
                    <td><?= $transaction['from_account_id'] ?></td>
                    <td><?= $transaction['to_account_id'] ?></td>
                    <td><?= $transaction['date'] ?></td>
            </tr>

        <?php endforeach ?>
            
    </table>

</div>

<a href="logout">Logout</a>
</body>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script>
    
    const accountNumber = (event) => {

        const accountNumber = event.attr('data-accountNumberBtn');
        $('#accountNumberForTransact').val(accountNumber);

    }

</script>